from django.urls import path
from . import views
from .views import paymentfunction, view_payment_page

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('contactpage',views.contactpage,name='contactpage'),
    path('servicepage',views.servicepage,name='servicepage'),
    path('loginpage',views.loginpage,name='loginpage'),
    path('login_function',views.login_function,name='login_function'),
    path('adminpage',views.adminpage,name='adminpage'),
    path('logout',views.logout,name='logout'),
    path('signuppage',views.signuppage,name='signuppage'),
    path('signup_patient',views.signup_patient,name='signup_patient'),
    path('loginpage',views.loginpage,name='loginpage'),
    path('view_patients', views.view_patients, name='view_patients'),
    path('add_doctor', views.add_doctor, name='add_doctor'),
    path('register_doctor', views.register_doctor, name='register_doctor'),
    path('view_doctors', views.view_doctors, name='view_doctors'),
    path('logoutadmin', views.logoutadmin, name='logoutadmin'),
    path('dochomepage', views.dochomepage, name='dochomepage'),
    path('editdocpage/<int:doctor_id>', views.editdocpage, name='editdocpage'),
    path('edit_doctor/<int:doctor_id>/', views.edit_doctor, name='edit_doctor'),
    path('delete_doctor/<int:doctor_id>/', views.delete_doctor, name='delete_doctor'),
    path('appointment/new/', views.create_appointment, name='create_appointment'),
    path('adminview_appointments', views.adminview_appointments, name='adminview_appointments'),
    path('profile/', views.profile, name='profile'),
    path('about', views.about, name='about'),
    path('create_prescription', views.create_prescription, name='create_prescription'),
    path('priscriptionpage', views.prescriptionpage, name='prescriptionpage'),
    path('view_prescriptions/', views.view_prescriptions, name='view_prescriptions'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('edit_profilepage', views.edit_profilepage, name='edit_profilepage'),
    path('book_appointmentpage', views.book_appointmentpage, name='book_appointmentpage'),
    path('create_appointmentpage/<int:doctor_id>/', views.create_appointmentpage, name='create_appointmentpage'),
    path('delete_appointments/',views. delete_appointments, name='delete_appointments'),
    path('payment_page', views.payment_page, name='payment_page'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('paymentfunction',views.paymentfunction,name='paymentfunction'),
    path('paymenthandler',views.paymenthandler,name='paymenthandler'),
    path('viewpaymentpage/', view_payment_page, name='view_payment_page'),
    path('payments/delete/<int:payment_id>/', views.delete_payment, name='delete_payment'),
    path('doctor/appointments/',views. doctor_appointments, name='doctor_appointments'),
    path('appointment/<int:appointment_id>/<str:status>/', views.update_appointment_status, name='update_appointment_status'),
    path('patient_appointments/', views.patient_appointments, name='patient_appointments'),
    path('delete_patients/', views.delete_patients, name='delete_patients'),
    path('delete_patient/<int:patient_id>/', views.delete_patient, name='delete_patient'),
    path('prescriptions/delete/<int:prescription_id>/', views.delete_prescription, name='delete_prescription'),
    path('appointment-success/', views.appointment_success, name='appointment_success'),
    path('create_receipt', views.create_receipt, name='create_receipt'),
    path('create_receiptpage/', views.create_receiptpage, name='create_receiptpage'),
    path('delete-receipt/<int:receipt_id>/', views.delete_receipt, name='delete_receipt'),
    path('view_receiptpage/', views.view_receiptpage, name='view_receiptpage'),
    path('patient_viewreceipt', views.patient_viewreceipt, name='patient_viewreceipt'),
    path('delete_appointment/<int:appointment_id>/', views.delete_appointment, name='delete_appointment'),
    path('delete_prescription/<int:prescription_id>/', views.delete_prescription, name='delete_prescription'),
]